[manager.shsh]
supports_multi_pkgs = false
list_cmd = "shsh list"
install_cmd = "python tt.py {}"
# install_cmd = "shsh install {}"
remove_cmd = "shsh uninstall {}"

[manager.fisher]
supports_multi_pkgs = true
list_cmd = "fish -c 'fisher list'"
install_cmd = "fish -c 'fisher install {}'"
remove_cmd = "fish -c 'fisher remove {}'"

